dist: bionic
language: python
sudo: false

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

addons:
  apt:
    packages:
      - libsasl2-dev
      - libssl-dev
      - libdb-dev

before_script:
  - export TZ=Europe/Vienna

install:
  - virtualenv .
  - bin/pip install coverage
  - bin/pip install coveralls
  - bin/pip install pyramid==1.9.4
  - |
    if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then
        bin/pip install repoze.zcml==0.4
        bin/pip install repoze.workflow==0.6.1
        bin/pip install Pillow==6.2.2
        bin/pip install natsort==6.2.0
    else
        bin/pip install repoze.zcml==1.1
        bin/pip install repoze.workflow==1.1
    fi
  - bin/pip install --upgrade pip setuptools zc.buildout
  - bin/buildout -N

script:
  - bin/py -m cone.ldap.tests.__init__
  - bin/coverage run --source src/cone/ldap -m cone.ldap.tests.__init__
  - bin/coverage report

after_success:
  - bin/coveralls
