factory: form
name: ugm_general_settings
props:
    action: context.form_action
    class: ajax
widgets:
- users_heading:
    factory: tag
    props:
        tag: h3
        text: i18n:user_properties_heading:Users Properties
- users_account_expiration:
    factory: field:label:checkbox
    value: expr:context.model.attrs.users_account_expiration == 'True'
    props:
        label: i18n:user_accounts_expires:User Accounts expires?
        help: i18n:user_accounts_expires_help:Flag whether to consider user expiration
- users_expires_attr:
    factory: field:label:text
    value: expr:context.model.attrs.users_expires_attr
    props:
        label: i18n:attribute_containing_expiration_time:Attribute containing expiration Time
        help: i18n:attribute_containing_expiration_time_help:Attribute name containing expires information
- users_expires_unit:
    factory: field:label:select
    value: expr:int(context.model.attrs.users_expires_unit)
    props:
        label: i18n:account_expiration_unit:Account expiration unit
        help: i18n:account_expiration_unit_help:Unit of expiration value
        vocabulary: expr:((0, 'Days since Epoch'), (1, 'Seconds since epoch'))
- user_id_autoincrement:
    factory: field:label:checkbox
    value: expr:context.model.attrs.user_id_autoincrement == 'True'
    props:
        label: i18n:autoincrement_user_id:Autoincrement user ID
        help: i18n:autoincrement_user_id_help:Flag whether to autoincrement user IDs at user creation time. This feature only works for systems using numeric user IDs
- user_id_autoincrement_prefix:
    factory: field:label:text
    value: expr:context.model.attrs.user_id_autoincrement_prefix
    props:
        label: i18n:autoincrement_user_id_prefix:Autoincrement user ID prefix
        help: i18n:autoincrement_user_id_prefix_help:Prefix for autogenerated user ID's
- user_id_autoincrement_start:
    factory: field:label:error:number
    value: expr:int(context.model.attrs.user_id_autoincrement_start)
    props:
        label: i18n:autoincrement_initial_user_number:Autoincrement initial user number
        help: i18n:autoincrement_initial_user_number_help:User number to start from
        datatype: integer
- users_portrait:
    factory: field:label:checkbox
    value: expr:context.model.attrs.users_portrait == 'True'
    props:
        label: i18n:portrait_support:Portrait Support
        help: i18n:portrait_support_help:Flag whether users can have a portrait
- users_portrait_attr:
    factory: field:label:text
    value: expr:context.model.attrs.users_portrait_attr
    props:
        label: i18n:attribute_containing_portrait_image:Attribute containing portrait image
        help: i18n:attribute_containing_portrait_image_help:Attribute name containing portrait image
- users_portrait_accept:
    factory: field:label:text
    value: expr:context.model.attrs.users_portrait_accept
    props:
        label: i18n:portrait_mimetype:Portrait mimetype
        help: i18n:portrait_mimetype_help:Accepted Image mimetype for portrait property
- users_portrait_width:
    factory: field:label:error:number
    value: expr:int(context.model.attrs.users_portrait_width)
    props:
        label: i18n:portrait_width:Portrait width
        help: i18n:portrait_width_help:Width in pixel portrait gets scaled to
        datatype: integer
- users_portrait_height:
    factory: field:label:error:number
    value: expr:int(context.model.attrs.users_portrait_height)
    props:
        label: i18n:portrait_height:Portrait height
        help: i18n:portrait_height_help:Height in pixel portrait gets scaled to
        datatype: integer
- users_local_management_enabled:
    factory: field:label:checkbox
    value: expr:context.model.attrs.users_local_management_enabled == 'True'
    props:
        label: i18n:users_local_management_enabled:Local User Management
        help: i18n:users_local_management_enabled_help:Enable local User Management
- users_exposed_attributes:
    factory: field:label:array
    value: expr:context.model.attrs.users_exposed_attributes
    props:
        label.label: i18n:exposed_attributes_label:User attributes exposed to attribute map
        array.label: i18n:exposed_attributes_array:Click '+' to add attributes
        help: i18n:exposed_attributes_help:Attributes which can be set via remote API
        sort: False
    widgets:
    - exposed:
        factory: error:text
        props:
            label: i18n:exposed_attributes_attribute:Attribute
            required: i18n:exposed_attributes_attribute_required:No attribute given
- users_form_attrmap:
    factory: field:label:dict
    value: expr:context.model.attrs.users_form_attrmap
    props:
        label: i18n:user_form_attributes:User form attributes
        help: i18n:user_form_attributes_help:Attributes exposed in user form
        key_label: i18n:principal_attr_name:Attribute name
        value_label: i18n:form_label:Form label
- users_listing_columns:
    factory: field:label:dict
    value: expr:context.model.attrs.users_listing_columns
    props:
        label: i18n:column_configuration_for_user_listings:Column configuration for user listings
        help: i18n:column_configuration_for_user_listings_help:Attributes shown in user listing
        required: i18n:column_configuration_for_user_listings_required:Column configuration for user listings values are mandatory
        key_label: i18n:principal_attr_name:Attribute name
        value_label: i18n:display_name:Display name
- users_listing_default_column:
    factory: field:label:text
    value: expr:context.model.attrs.users_listing_default_column
    props:
        label: i18n:users_listing_default_column:Users listing default column
        help: i18n:users_listing_default_column_help:Default sort column in user listing
- groups_heading:
    factory: tag
    props:
        tag: h3
        text: i18n:groups_properties_heading:Groups Properties
- groups_form_attrmap:
    factory: field:label:dict
    value: expr:context.model.attrs.groups_form_attrmap
    props:
        label: i18n:group_form_attributes:Group form attributes
        key_label: i18n:principal_attr_name:Attribute name
        value_label: i18n:form_label:Form label
- groups_listing_columns:
    factory: field:label:dict
    value: expr:context.model.attrs.groups_listing_columns
    props:
        label: i18n:column_configuration_for_groups_listings:Column configuration for groups listings
        required: i18n:column_configuration_for_groups_listings_required:Column configuration for group listings value is mandatory
        key_label: i18n:principal_attr_name:Attribute name
        value_label: i18n:display_name:Display name
- groups_listing_default_column:
    factory: field:label:text
    value: expr:context.model.attrs.groups_listing_default_column
    props:
        label: i18n:groups_listing_default_column:Groups listing default column
- save:
    factory: submit
    props:
        action: save
        expression: True
        handler: context.save
        next: context.next
        label: i18n:save:Save