factory: form
name: ugm_general
props:
    action: context.form_action
    class: ajax
widgets:
- users_heading:
    factory: tag
    props:
        tag: h3
        text: i18n:user_properties_heading:Users Properties
- users_account_expiration:
    factory: field:label:checkbox
    value: expr:context.model.attrs.users_account_expiration == 'True'
    props:
        label: i18n:user_accounts_expires
        help: i18n:user_accounts_expires_help
- users_expires_attr:
    factory: field:label:text
    value: expr:context.model.attrs.users_expires_attr
    props:
        label: i18n:attribute_containing_expiration_time
        help: i18n:attribute_containing_expiration_time_help
- users_expires_unit:
    factory: field:label:select
    value: expr:int(context.model.attrs.users_expires_unit)
    props:
        label: i18n:account_expiration_unit
        help: i18n:account_expiration_unit_help
        vocabulary: expr:((0, 'Days since Epoch'), (1, 'Seconds since epoch'))
- user_id_autoincrement:
    factory: field:label:checkbox
    value: expr:context.model.attrs.user_id_autoincrement == 'True'
    props:
        label: i18n:autoincrement_user_id
        help: i18n:autoincrement_user_id_help
- user_id_autoincrement_prefix:
    factory: field:label:text
    value: expr:context.model.attrs.user_id_autoincrement_prefix
    props:
        label: i18n:autoincrement_user_id_prefix
        help: i18n:Prefix for autogenerated user ID's
- user_id_autoincrement_start:
    factory: field:label:error:number
    value: expr:int(context.model.attrs.user_id_autoincrement_start)
    props:
        label: i18n:autoincrement_initial_user_number
        help: i18n:autoincrement_initial_user_number_help
        datatype: integer
- users_portrait:
    factory: field:label:checkbox
    value: expr:context.model.attrs.users_portrait == 'True'
    props:
        label: i18n:portrait_support
        help: i18n:portrait_support_help
- users_portrait_attr:
    factory: field:label:text
    value: expr:context.model.attrs.users_portrait_attr
    props:
        label: i18n:attribute_containing_portrait_image
        help: i18n:attribute_containing_portrait_image_help
- users_portrait_accept:
    factory: field:label:text
    value: expr:context.model.attrs.users_portrait_accept
    props:
        label: i18n:portrait_mimetype
        help: i18n:portrait_mimetype_help
- users_portrait_width:
    factory: field:label:error:number
    value: expr:int(context.model.attrs.users_portrait_width)
    props:
        label: i18n:portrait_width
        help: i18n:portrait_width_help
        datatype: integer
- users_portrait_height:
    factory: field:label:error:number
    value: expr:int(context.model.attrs.users_portrait_height)
    props:
        label: i18n:portrait_height
        help: i18n:portrait_height_help
        datatype: integer
- users_local_management_enabled:
    factory: field:label:checkbox
    value: expr:context.model.attrs.users_local_management_enabled == 'True'
    props:
        label: i18n:users_local_management_enabled
        help: i18n:users_local_management_enabled_help
- users_form_attrmap:
    factory: field:label:dict
    value: expr:context.model.attrs.users_form_attrmap
    props:
        label: i18n:user_form_attributes
        help: i18n:user_form_attributes_help
        key_label: i18n:principal_attr_name
        value_label: i18n:form_label
- users_listing_columns:
    factory: field:label:dict
    value: expr:context.model.attrs.users_listing_columns
    props:
        label: i18n:column_configuration_for_user_listings
        help: i18n:column_configuration_for_user_listings_help
        required: i18n:column_configuration_for_user_listings_required
        key_label: i18n:principal_attr_name
        value_label: i18n:display_name
- users_listing_default_column:
    factory: field:label:text
    value: expr:context.model.attrs.users_listing_default_column
    props:
        label: i18n:users_listing_default_column
        help: i18n:users_listing_default_column_help
- users_exposed_attributes:
    factory: field:label:array
    value: expr:context.model.attrs.users_exposed_attributes
    props:
        label.label: i18n:exposed_attributes_label
        array.label: i18n:exposed_attributes_array
        help: i18n:exposed_attributes_help
        sort: False
    widgets:
    - exposed:
        factory: error:text
        props:
            label: i18n:exposed_attributes_attribute
            required: i18n:exposed_attributes_attribute_required
- groups_heading:
    factory: tag
    props:
        tag: h3
        text: i18n:groups_properties_heading:Groups Properties
- groups_form_attrmap:
    factory: field:label:dict
    value: expr:context.model.attrs.groups_form_attrmap
    props:
        label: i18n:group_form_attributes
        key_label: i18n:principal_attr_name
        value_label: i18n:form_label
- groups_listing_columns:
    factory: field:label:dict
    value: expr:context.model.attrs.groups_listing_columns
    props:
        label: i18n:column_configuration_for_groups_listings
        required: i18n:column_configuration_for_groups_listings_required
        key_label: i18n:principal_attr_name
        value_label: i18n:display_name
- groups_listing_default_column:
    factory: field:label:text
    value: expr:context.model.attrs.groups_listing_default_column
    props:
        label: i18n:groups_listing_default_column
- roles_heading:
    factory: tag
    props:
        tag: h3
        text: i18n:roles_properties_heading:Roles Properties
- save:
    factory: submit
    props:
        action: save
        expression: True
        handler: context.save
        next: context.next
        label: i18n:save