factory: form
name: ldap_groups_settings
props:
    action: context.form_action
    class: ajax
widgets:
- groups_dn:
    factory: field:label:error:text
    value: expr:context.model.attrs.groups_dn
    props:
        label: i18n:groups_container_dn
        required: i18n:groups_container_dn_required
- groups_scope:
    factory: field:label:select
    value: expr:context.model.attrs.groups_scope
    props:
        label: i18n:groups_search_scope
        vocabulary: expr:context.scope_vocab
- groups_query:
    factory: field:label:text
    value: expr:context.model.attrs.groups_query
    props:
        label: i18n:groups_search_query_filter
- groups_object_classes:
    factory: field:label:text
    value: expr:u', '.join(context.model.attrs.get('groups_object_classes', []))
    props:
        label: i18n:object_classes_for_group_creation
- groups_aliases_attrmap:
    factory: field:label:error:dict
    value: expr:context.groups_aliases_attrmap
    props:
        label: i18n:group_attribute_aliases
        required: i18n:group_attribute_aliases_required
        static: True
        key_label: i18n:reserved_key
        value_label: i18n:ldap_attr_name
#- groups_relation:
#    factory: field:label:text
#    value: expr:context.model.attrs.groups_relation
#    props:
#        label: Group-member-relation
- save:
    factory: submit
    props:
        action: save
        expression: True
        handler: context.save
        next: context.next
        label: i18n:save